# Site settings
author: Timur Mishiev
title: Timur's Blog
header-img: img/home-bg.png
email: timurmishiev@gmail.com
copyright_name: Timur Mishiev
description: > # this means to ignore newlines until "baseurl:"
  learn... code... sleep... eat... repeat ...
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Starcatch

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
